### ISSUE TITLE
angular not defined

### ISSUE THREAD

**Issue by johnryan** [MikePreston17/nugs#2]
Very cool project! I'm getting:

```
Uncaught ReferenceError: angular is not defined
```

on nugs.net - is it possible they no longer use angular / can you recommend a different bookmark snippet to try?

**Comment by MikePreston17** [comment]
Hi Ryan,

First, I'm not on nugs.net, but [this](nugs.vercel.app/)
Second, this is a Vue js project, not an angular one.

Hope this helps.
